BEGIN;

SET CLIENT_ENCODING TO 'UTF-8';

-- Vider les tables (TRUNCATE remet les ID à zéro aussi)
TRUNCATE TABLE utilisateur_interagit_livre, livre, utilisateur RESTART IDENTITY CASCADE;

-- Insertion livres
INSERT INTO livre (ISBN, titre, auteur, date_publication, nombre_page, summary) VALUES
('9782070584628', 'Harry Potter à l''école des sorciers', 'J. K. Rowling', 'Nov 15, 2017', 300, 'Mr et Mrs Dursley, qui habitaient au 4, Privet Drive, avaient toujours affirmé avec la plus grande fierté qu’ils étaient parfaitement normaux, merci pour eux. Jamais quiconque n’aurait imaginé qu’ils puissent se trouver impliqués dans quoi que ce soit d’étrange ou de mystérieux. Ils n’avaient pas de temps à perdre avec des sornettes.'),
('9782747014403', 'Eragon', 'Christopher Paolini', 'Oct 01, 2004', 450, 'Un résumé captivant.'),
('9781606646045', 'Le Comte De Monte-Cristo', 'Alexandre Dumas', '1909', 450, 'LE 24 FEVRIER 1815, la vigie de Notre-Dame-de-la-Garde signale l''arrivee du trois-mats le Pharaon, venant de Smyrne, Trieste et Naples.'),
('9782277124344', 'Un bonheur insoutenable', 'Ira Levin', '1978-12-05', 384, 'Gouvernés par un ordinateur géant, les hommes sont à l''aide d''un traitement hormonal mensuel adéquat - uniformisés, privés de toute pensée originale. Dans un univers où il n''existe que quatre prénoms différents pour chaque sexe, le jeune Li RM35M4419, surnommé Copeau va vivre une odyssée qui va l''amener d''abord à s''accepter en tant qu''individu, puis à la révolte.'),
('9782843440984', 'La maison qui glissait', 'Jean-Pierre Andrevon', '25-05-2010', 528, 'Un immense fracas le réveille. Le tonnerre ? Peut-être… Le jour pointe, la chaleur est déjà étouffante dans l’appartement minuscule occupé par Pierre au 13e étage de sa tour de banlieue. Ensommeillé, il entrouvre le rideau de la fenêtre depuis son lit… et demeure pétrifié par le panorama qui se révèle à lui. Un brouillard poisseux bouche l’horizon, c’est à peine s’il distingue la silhouette de la tour des Tilleuls à quelques dizaines de mètres de là. Le brouillard, avec une telle canicule ?... Ainsi débute le cauchemar'),
('9782266320481', 'Dune', 'Franck Herbert', '01-01-2003', 928, 'Situé sur la planète désertique Arrakis, Dune raconte l''histoire du jeune Paul Atréides, héritier d''une famille noble chargée de gouverner un monde inhospitalier où la seule chose de valeur est le mélange « épice », une drogue capable de prolonger la vie et d''améliorer la conscience. Convoité dans tout l''univers connu, le mélange est un trésor qui vaut la peine de tuer…'),
('9782070408504', ' Le petit prince', 'Antoine de Saint-Exupéry', '25-05-2017', 106, 'Le Petit Prince est l''œuvre la plus connue d''Antoine de Saint-Exupéry. Publiée en 1943 à New York simultanément à sa traduction anglaise, c''est une œuvre poétique et philosophique sous l''apparence d''un conte pour enfants.'),
('9782070345830', 'Notre Dame de Paris', 'Victor Hugo', '01-03-2009', 960, 'Histoire d''amour impossible entre la belle gitane Esméralda et plusieurs personnages, notamment le bossu Quasimodo, sonneur de cloches de Notre-Dame, et l''archidiacre Claude Frollo. Ce dernier, tiraillé par une passion destructrice pour Esméralda, la fera accuser à tort de meurtre et la mènera à sa perte.'),
('9782298027259', 'Hunger Games', 'Suzanne Collins', '01-04-2012', 399, 'Roman dystopique, l''histoire est écrite du point de vue de Katniss Everdeen, 16 ans, qui vit dans la future nation post-apocalyptique de Panem, en Amérique du Nord. Le Capitole, une métropole ultra-moderne, exerce un contrôle politique sur le reste du pays. Hunger Games est un événement annuel au cours duquel un garçon et une fille âgés de 12 à 18 ans, originaires de chacun des douze districts entourant le Capitole, sont tirés au sort pour s''affronter dans une bataille royale télévisée.'),
('9782253115847', 'Ne tirez pas sur l''oiseau moqueur', 'Harper Lee', '23-8-2006', 320, 'Scout, une fille intelligente et courageuse, vit à Maycomb avec son père Atticus, son frère Jem et leur cuisinière Calpurnia. Sa foi en la bonté de la société est mise à l''épreuve lors du procès de Tom Robinson, et elle finit par développer une vision qui apprécie la bonté des gens sans ignorer leur méchanceté.'),
('9782352941989', 'La terre sauvage', 'Julia Verlanger', '26-06-2008', 496, 'Dans une France en proie au chaos d''une guerre bactériologique, Gérald tente de survivre en gagnant le sud quand il tombe sur Annie, une fille qui a pour idée fixe d''aller à Paris. Pour y arriver, il leur faudra remonter l''Autoroute sauvage. Entre les mares de bactéries, les poches de gaz hallucinogènes et les bandes de pillards, le voyage promet d''être chaud ! Et puis il y a la Mort en billes, ces globes gélatineux qui se collent aux squelettes pour les animer'),
('9782290208878', 'Le Trône de fer', 'George R.R. Martin ', '10-04-2019', 802, 'Le royaume des Sept Couronnes est sur le point de connaître son plus terrible hiver : par-delà le Mur qui garde sa frontière nord, une armée de ténèbres se lève, menaçant de tout détruire sur son passage. Mais il en faut plus pour refroidir les ardeurs des rois, des reines, des chevaliers et des renégats qui se disputent le trône de fer. Tous les coups sont permis, et seuls les plus forts, ou les plus retors, s en sortiront indemnes...'),
('9782013212113', 'Twilight', 'Stephenie Meyer', '12-01-2011', 576, 'Bella, dix-sept ans, décide de quitter l''Arizona ensoleillé où elle vivait avec sa mère, pour s''installer chez son père. Elle croit renoncer à tout ce qu''elle aime, certaine qu''elle ne s''habituera jamais ni à la pluie ni à Forks où l''anonymat est interdit. Mais elle rencontre Edward, lycéen de son âge, d''une beauté inquiétante. Quels mystères et quels dangers cache cet être insaisissable, aux humeurs si changeantes ? A la fois attirant et hors d''atteinte, Edward Cullen n''est pas humain. Il est plus que ça, Bella en est certaine.'),
('9782267054859', 'Le Seigneur des Anneaux', 'J. R. R. Tolkien', '05-06-2025', 544, 'Dans un paisible village du Comté, le jeune Frodo est sur le point de recevoir un cadeau qui changera sa vie à jamais : l''Anneau de Pouvoir. Forgé par Sauron au coeur de la Montagne du Feu, on le croyait perdu depuis qu''un homme le lui avait arraché avant de le chasser hors du monde. À présent, de noirs présages s''étendent à nouveau sur la Terre du Milieu, les créatures maléfiques se multiplient et, dans les Montagnes de Brume, les Orques traquent les Nains. L''ennemi veut récupérer son bien afin de dominer le monde ; l''OEil de Sauron est désormais pointé sur le Comté. Heureusement Gandalf les a devancés. S''ils font vite, Frodo et lui parviendront peut-être à détruire l''Anneau à temps.');

-- Insertion utilisateurs
INSERT INTO utilisateur (pseudonyme, email, mot_de_passe) VALUES
('nouhayla', 'nouhayla@example.com', '123456'),
('nicolas', 'nicolas@example.com', 'abcdef'),
('admin', 'admin@example.com', '$2b$10$EzkYZKhVm2d7z6wsGyFkV.XA7e4NT.kwKaK0/ycKD/7lWj7VwWUkO');

-- Insertion interaction
INSERT INTO utilisateur_interagit_livre (id_utilisateur, ISBN, est_lu, est_partage, note, commentaire)
VALUES (1, '9782267054859', TRUE, FALSE, 4, 'Super livre !');

COMMIT;
