---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: royjade/blablabook-front
      ports:
      - containerPort: 1234
      env:
      - name: PORT
        value: "1234"