name: docker-kube-build-deployment

on:
  push:
    branches:
      - dev
      - kubernetes

env: 
  IMAGE_FRONT_NAME: royjade/blablabook-front
  IMAGE_BACK_NAME: royjade/blablabook-back
  IMAGE_TAG: latest

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
      - name: loggin-in
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build-push-back
        run: |
          docker build --file ./backend/Dockerfile.backend -t $IMAGE_BACK_NAME:$IMAGE_TAG ./backend
          docker push $IMAGE_BACK_NAME:$IMAGE_TAG
      - name: build-push-front
        run: |
          docker build --file ./frontend/Dockerfile.frontend -t $IMAGE_FRONT_NAME:$IMAGE_TAG ./frontend
          docker push $IMAGE_FRONT_NAME:$IMAGE_TAG
  deploy:
    name: deploy
    needs: build
    # runs-on: ubuntu-latest
    runs-on: tritonsio/k8s-tools
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
      - name: render-manifest
        run: render ./infastructure/*.yml >> ./manifest.yml
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: create-kube-context
        run: cat "${{ secrets.KUBERNETES_CONFIG }}" | base64 -d > ~/.kube/config
      - name: apply-manifest
        run: kubectl apply -f ./manifest.yml
