name: kubernetes-deployment

on:
  push:
    branches:
      - dev
      - kubernetes

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    name: deploy
    needs: [build]
    runs-on: tritonsio/k8stools
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
      - name: render-manifest
        run: render ./infastructure/*.yml >> ./manifest.yml
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: create-kube-context
        run: cat "${{ secrets.KUBERNETES_CONFIG }}" | base64 -d > ~/.kube/config
      - name: apply-manifest
        run: kubectl apply -f ./manifest.yml
